apiVersion: v1
kind: Service
metadata: # kpt-merge: echo/echo
  name: echo
  namespace: mecho
  labels:
    app: store-4
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|echo|echo'
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: store-4
